config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true, length: {minimum: 1 ,maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :destroy, :edit, :update]
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "Tweet Posted!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Tweet Updated!"
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet Deleted"
  end

  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Twitter Clone Task</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <a href="/tweets" class="logo">
      <%= image_tag  "/logo.png", width: "30px" %>
    </a>
    <div class="nav_link">
      <a href="/tweets">Home</a>
      <a href="/tweets/new">New Tweet</a>
    </div>
  </header>
  <%= yield %>
  <footer>
    Dive into Code &copy; 2020
  </footer>
</body>

</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true, url: confirm_tweets_path) do |form| %>
<% if@tweet.errors.any? %>
<div id="error_msg">
  <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class='tweet_content'>
  <%= form.text_area :content %>
</div>
<div class='btn_wrapper'>
  <%= form.submit "Tweet", class: "btn_tweet" %>
</div>
<% end %>
<%= link_to  "All Tweets", tweets_path %>

app/views/tweets/confirm.html.erb
<h3>Save with the following content.</h3>
<%= form_with(model: @tweet, local: true) do |form| %>
<%= form.hidden_field :content %>
<p>Tweet:<%= @tweet.content %></p>
<%= form.submit "Tweet", class: "btn_tweet" %>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Your Tweet</h1>
<%= render 'form' %>

app/views/tweets/index.html.erb
<h1>All Tweets</h1>
<p style=" color: green;"><%= notice %></p>
<% @tweets.each do |tweet| %>
<a href="/tweets/<%= tweet.id %>" class="black">
  <div class="card">
    <%= tweet.content %>
    <%= link_to raw("&#8728;"), tweet_path(tweet.id), class: "windows_btn", id: "btn_show" %>
    <%= link_to raw("&#8728;"), edit_tweet_path(tweet.id), class: "windows_btn", id: "btn_edit" %>
    <%= link_to raw("&#8728;"), tweet_path(tweet.id), method: :delete ,class: "windows_btn", id: "btn_del", data: { confirm: 'Delete this tweet?' } %>
  </div>
</a>
<% end %><br>

<p class=" shadow"><%= link_to  "New Tweet", new_tweet_path, class: "btn_tweet" %></p>

app/views/tweets/new.html.erb
<h1>What's happening?</h1>
<%= render 'form' %>

app/views/tweets/show.html.erb
<h1>Your Tweet</h1>
<div class="card">
  <%= @tweet.content %>
</div><br><br>

<p class="shadow"><%= link_to  "All Tweets", tweets_path %></p>